version: "3"
services:
  kali:
    image: kalilinux/kali-rolling:latest
    
    networks: 
      lab:
        ipv4_address: "192.168.5.2"
    
        
  alpine:
    image: alpine:latest
    ports:
      - 22:22
    networks:
      lab:
        ipv4_address: 192.168.5.4
  
  couchdb:
    image: vulhub/couchdb:1.6.0
    ports:
      - 5984:5984
    networks:
      lab:
        ipv4_address: 192.168.5.10

networks:
  lab:
    ipam:
      driver: default
      config:
        - subnet: "192.168.5.0/24"
