version: "3"
services:
    kali:
        image: kalilinux/kali-rolling:latest
        container_name: kali
        networks:
            vpc:
                ipv4_address: 192.168.10.2
        tty: true

    alpine:
        image: alpine:latest
        container_name: alpine
        ports:
            - 22:22
        networks:
            vpc:
                ipv4_address: 192.168.10.3
        tty: true


networks:
    vpc:
        ipam:
            driver: default
            config:
                - subnet: "192.168.10.0/24"
